### ISSUE TITLE
Feature Request: Web Hook setting

### ISSUE THREAD

**Issue by NikRimington** [KevinJump/Our.Umbraco.SilentUpgrade#1]
Hey Kevin,

Amazing package! I was reading a twitter thread about it and had an idea as a big use case of this is CI/CD pipelines. Would it be possible to have a setting where you can define a web hook URL.

The package could then push values to the web hook depending on if it is successful or if it fails.

My thoughts are it pushes the following:

```

{
    site: 'https:XYZ', //maybe this comes from the umbracosettings.xml file or from an app setting specific to this package
    autoUpgradeSuccessful: true/false
    message: error message if failed, or maybe a version from/to message if successful
}

```

Just a thought :-)

**Comment by KevinJump** [comment]
yeah, my immediate thought it event hooks, so you could listen for this then do what you want.

**Comment by NikRimington** [comment]
Yeah that could work. If you did that then someone else could create a package for the webhooks side of things if they wanted to :-) But something to allow for feedback when used in the automated approach would be cool :-)

**Comment by KevinJump** [comment]
https://github.com/KevinJump/Our.Umbraco.SilentUpgrade/commit/3704944ecd80222cc6a00d4bc343bf792357326e - UpgradeStarting and UpgradeComplete events. 

something like: 
```
SilentUpgrade.UpgradeComplte += upgradeCompleted;
```
Passes start version and end version, (and a message if we have one). 

Would need docs on how you register your own composer (so you would only want it to register at runtime.Upgrade and after the SilentUpgrade one.

but this would probably do it?

**Comment by KevinJump** [comment]
also fire when their is a failure https://github.com/KevinJump/Our.Umbraco.SilentUpgrade/commit/498b12c2c9ceae0c764d670731ca3d4eae2e9c7e

although because we fallback to the installer screen this is more likely a warning that you need to go look at the site and sort it out?

**Comment by NikRimington** [comment]
Yeah that would work think. Would cover the important things I think. Gives a nice way for people to interact with it :-)

**Comment by KevinJump** [comment]
this works now, and I've released an update with it in and everything.
